export { default as formzillion } from "public/logos/logo_icon.png";
export { default as sendgrid } from "public/brands/sendgrid.png";
export { default as slack } from "public/brands/slack.png";
export { default as mailchimp } from "public/brands/mailchimp.png";
export { default as mailerlite } from "public/brands/mailerlite.png";
export { default as webhooks } from "public/brands/webhooks.png";
export { default as freshdesk } from "public/brands/freshdesk.png";
export { default as airtable } from "public/brands/airtable.png";
export { default as convertkit } from "public/brands/convertkit.png";
